/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/F0sjqrQVf5x
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import { Progress } from "@/components/ui/progress"

export function UploadInformation() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md p-6 space-y-4">
        <h1 className="text-3xl font-bold text-center">Upload File</h1>
        <div className="flex items-center justify-center space-x-2">
          <Label className="cursor-pointer" htmlFor="file">
            <UploadIcon className="h-6 w-6" />
            <span className="sr-only">Upload File</span>
          </Label>
          <Input className="hidden" id="file" type="file" />
        </div>
        <div className="border border-gray-200 rounded-lg p-4">
          <h2 className="text-lg font-semibold">File Preview</h2>
          <div className="mt-2">
            <div className="flex items-center gap-2">
              <FileIcon className="h-6 w-6" />
              <span>File Name</span>
            </div>
            <div className="mt-2">
              <Progress className="h-1 w-full bg-gray-200 rounded-full" max={100} value={50} />
            </div>
          </div>
        </div>
        <Button className="w-full" type="submit">
          Upload
        </Button>
        <Button className="w-full" variant="outline">
          Cancel
        </Button>
      </div>
    </div>
  )
}


function UploadIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function FileIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}
