spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PWD_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  profiles:
    default: deploy
  jackson:
    property-naming-strategy: SNAKE_CASE
openai:
  api:
    key: ${OPENAI_API_KEY}

website:
  base-url:
    frontend: https://equity-ai.vercel.app/